
---
# tasks/main.yml

- name: Installer MariaDB
  ansible.builtin.apt:
    name: mariadb-server
    state: present
    update_cache: yes
  become: true

- name: Déployer le fichier de configuration personnalisé
  ansible.builtin.template:
    src: mariadb.cnf.j2
    dest: /etc/mysql/mariadb.conf.d/50-server.cnf
    owner: root
    group: root
    mode: '0644'
  notify: Redémarrer MariaDB
  become: true

- name: Activer et démarrer le service MariaDB
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: true
  become: true

- name: Autoriser MariaDB dans UFW (si UFW actif)
  ansible.builtin.shell: |
    ufw status | grep -q "Status: active" && ufw allow 3306/tcp || true
  changed_when: false
  become: true

- name: Vérifier que MariaDB écoute localement
  ansible.builtin.wait_for:
    host: "127.0.0.1"
    port: 3306
    state: started
    timeout: 30
  delegate_to: "{{ inventory_hostname }}"
  become: true
  changed_when: false

- meta: flush_handlers

